# Generated by Django 3.2.5 on 2021-07-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('is_bingo', models.BooleanField(default=False)),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('p3', models.IntegerField()),
                ('p4', models.IntegerField()),
                ('p5', models.IntegerField()),
                ('p6', models.IntegerField()),
                ('p7', models.IntegerField()),
                ('p8', models.IntegerField()),
                ('p9', models.IntegerField()),
                ('p10', models.IntegerField()),
                ('p11', models.IntegerField()),
                ('p12', models.IntegerField()),
                ('p13', models.IntegerField()),
                ('p14', models.IntegerField()),
                ('p15', models.IntegerField()),
                ('p16', models.IntegerField()),
                ('p17', models.IntegerField()),
                ('p18', models.IntegerField()),
                ('p19', models.IntegerField()),
                ('p20', models.IntegerField()),
                ('p21', models.IntegerField()),
                ('p22', models.IntegerField()),
                ('p23', models.IntegerField()),
                ('p24', models.IntegerField()),
                ('p25', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='bingoApp.admin')),
            ],
        ),
    ]
