# Generated by Django 3.2.5 on 2021-07-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='BingoAdmin',
        ),
    ]
