# Generated by Django 3.2.5 on 2021-07-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingoApp', '0002_rename_admin_bingoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='bingoApp.bingoadmin'),
        ),
    ]
