# Generated by Django 3.2.7 on 2021-12-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingoApp', '0004_auto_20211213_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visualized', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bingoApp.bingoadmin')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingoApp.card')),
            ],
        ),
    ]
