# Generated by Django 3.2.7 on 2021-12-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingoApp', '0005_bingonotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user_name',
            new_name='name',
        ),
    ]
